version: "3.8"
services:
  dev:
    build:
      context: .
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    container_name: python_dev
    image: python_dev
    #user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/app/src  # Comparte el código entre el host y el contenedor
    environment:
      - TERM=xterm-256color  # Para compatibilidad de terminal
    ports:
      - "8888:8888"  # Para Jupyter, si lo necesitas
      - "8000:8000"
      - "5000:5000"
      - "6000:6000"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
      - "6005:6005"
    stdin_open: true
    tty: true
